// Code generated by the Encore 1.50.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly admin: admin.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly avatar: avatar.ServiceClient
    public readonly credits: credits.ServiceClient
    public readonly fit: fit.ServiceClient
    public readonly library: library.ServiceClient
    public readonly tryon: tryon.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.admin = new admin.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.avatar = new avatar.ServiceClient(base)
        this.credits = new credits.ServiceClient(base)
        this.fit = new fit.ServiceClient(base)
        this.library = new library.ServiceClient(base)
        this.tryon = new tryon.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { listJobs as api_admin_jobs_listJobs } from "~backend/admin/jobs";
import { getMetrics as api_admin_metrics_getMetrics } from "~backend/admin/metrics";
import {
    listFlags as api_admin_moderation_listFlags,
    reviewFlag as api_admin_moderation_reviewFlag
} from "~backend/admin/moderation";
import { seed as api_admin_seed_seed } from "~backend/admin/seed";
import {
    checkJob as api_admin_test_nanobana_checkJob,
    testGemini as api_admin_test_nanobana_testGemini
} from "~backend/admin/test_nanobana";

export namespace admin {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.checkJob = this.checkJob.bind(this)
            this.getMetrics = this.getMetrics.bind(this)
            this.listFlags = this.listFlags.bind(this)
            this.listJobs = this.listJobs.bind(this)
            this.reviewFlag = this.reviewFlag.bind(this)
            this.seed = this.seed.bind(this)
            this.testGemini = this.testGemini.bind(this)
        }

        /**
         * Check job status endpoint for testing
         */
        public async checkJob(params: { job_id: string }): Promise<ResponseType<typeof api_admin_test_nanobana_checkJob>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/admin/check-job/${encodeURIComponent(params.job_id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_test_nanobana_checkJob>
        }

        /**
         * Gets usage statistics and metrics for admin dashboard.
         */
        public async getMetrics(): Promise<ResponseType<typeof api_admin_metrics_getMetrics>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/metrics`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_metrics_getMetrics>
        }

        /**
         * Lists moderation flags for admin review.
         */
        public async listFlags(params: RequestType<typeof api_admin_moderation_listFlags>): Promise<ResponseType<typeof api_admin_moderation_listFlags>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "flag_type": params["flag_type"],
                limit:       params.limit === undefined ? undefined : String(params.limit),
                offset:      params.offset === undefined ? undefined : String(params.offset),
                reviewed:    params.reviewed === undefined ? undefined : String(params.reviewed),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/moderation`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_moderation_listFlags>
        }

        /**
         * Lists try-on jobs for admin monitoring.
         */
        public async listJobs(params: RequestType<typeof api_admin_jobs_listJobs>): Promise<ResponseType<typeof api_admin_jobs_listJobs>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
                status: params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/jobs`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_jobs_listJobs>
        }

        /**
         * Marks a moderation flag as reviewed.
         */
        public async reviewFlag(params: RequestType<typeof api_admin_moderation_reviewFlag>): Promise<ResponseType<typeof api_admin_moderation_reviewFlag>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                reviewed: params.reviewed,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/moderation/${encodeURIComponent(params.id)}/review`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_moderation_reviewFlag>
        }

        /**
         * Creates demo content for testing purposes.
         */
        public async seed(): Promise<ResponseType<typeof api_admin_seed_seed>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_seed_seed>
        }

        /**
         * Test endpoint for Gemini API integration
         */
        public async testGemini(params: RequestType<typeof api_admin_test_nanobana_testGemini>): Promise<ResponseType<typeof api_admin_test_nanobana_testGemini>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/admin/test-gemini`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_test_nanobana_testGemini>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { deleteData as api_auth_delete_data_deleteData } from "~backend/auth/delete_data";
import { test as api_auth_test_test } from "~backend/auth/test";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteData = this.deleteData.bind(this)
            this.test = this.test.bind(this)
        }

        /**
         * Deletes all user data for GDPR compliance.
         */
        public async deleteData(): Promise<ResponseType<typeof api_auth_delete_data_deleteData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/data`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_delete_data_deleteData>
        }

        /**
         * Test endpoint to verify auth and database connection
         */
        public async test(): Promise<ResponseType<typeof api_auth_test_test>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/auth/test`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_test_test>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { complete as api_avatar_complete_complete } from "~backend/avatar/complete";
import { get as api_avatar_get_get } from "~backend/avatar/get";
import { upload as api_avatar_upload_upload } from "~backend/avatar/upload";

export namespace avatar {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.complete = this.complete.bind(this)
            this.get = this.get.bind(this)
            this.upload = this.upload.bind(this)
        }

        /**
         * Marks avatar as completed after successful file upload.
         */
        public async complete(params: RequestType<typeof api_avatar_complete_complete>): Promise<ResponseType<typeof api_avatar_complete_complete>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/avatar/complete`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_avatar_complete_complete>
        }

        /**
         * Retrieves avatar details and signed URLs.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_avatar_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/avatar/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_avatar_get_get>
        }

        /**
         * Uploads and processes a full-body photo to create an avatar.
         */
        public async upload(params: RequestType<typeof api_avatar_upload_upload>): Promise<ResponseType<typeof api_avatar_upload_upload>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/avatar`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_avatar_upload_upload>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    checkCredits as api_credits_credits_checkCredits,
    deductCredit as api_credits_credits_deductCredit,
    getCredits as api_credits_credits_getCredits,
    updatePlan as api_credits_credits_updatePlan
} from "~backend/credits/credits";
import { testScenario as api_credits_test_testScenario } from "~backend/credits/test";

export namespace credits {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.checkCredits = this.checkCredits.bind(this)
            this.deductCredit = this.deductCredit.bind(this)
            this.getCredits = this.getCredits.bind(this)
            this.testScenario = this.testScenario.bind(this)
            this.updatePlan = this.updatePlan.bind(this)
        }

        /**
         * Check if user has credits available for a new generation
         */
        public async checkCredits(): Promise<ResponseType<typeof api_credits_credits_checkCredits>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/credits/check`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_credits_credits_checkCredits>
        }

        /**
         * Deduct a credit when generation completes successfully
         */
        public async deductCredit(params: RequestType<typeof api_credits_credits_deductCredit>): Promise<ResponseType<typeof api_credits_credits_deductCredit>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/credits/deduct`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_credits_credits_deductCredit>
        }

        /**
         * Get user's current credit status
         */
        public async getCredits(): Promise<ResponseType<typeof api_credits_credits_getCredits>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/credits`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_credits_credits_getCredits>
        }

        /**
         * Test endpoint to simulate different credit scenarios
         */
        public async testScenario(params: RequestType<typeof api_credits_test_testScenario>): Promise<ResponseType<typeof api_credits_test_testScenario>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/credits/test`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_credits_test_testScenario>
        }

        /**
         * Update user's plan and recalculate credits
         */
        public async updatePlan(params: RequestType<typeof api_credits_credits_updatePlan>): Promise<ResponseType<typeof api_credits_credits_updatePlan>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/credits/update-plan`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_credits_credits_updatePlan>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { complete as api_fit_complete_complete } from "~backend/fit/complete";
import { get as api_fit_get_get } from "~backend/fit/get";
import { upload as api_fit_upload_upload } from "~backend/fit/upload";

export namespace fit {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.complete = this.complete.bind(this)
            this.get = this.get.bind(this)
            this.upload = this.upload.bind(this)
        }

        /**
         * Marks fit as completed after successful file upload.
         */
        public async complete(params: RequestType<typeof api_fit_complete_complete>): Promise<ResponseType<typeof api_fit_complete_complete>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/fits/complete`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fit_complete_complete>
        }

        /**
         * Retrieves fit details and signed URLs.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_fit_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/fits/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fit_get_get>
        }

        /**
         * Uploads a fit image.
         */
        public async upload(params: RequestType<typeof api_fit_upload_upload>): Promise<ResponseType<typeof api_fit_upload_upload>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/fits`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fit_upload_upload>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { listAvatars as api_library_avatars_listAvatars } from "~backend/library/avatars";
import { listFits as api_library_fits_listFits } from "~backend/library/fits";
import { listResults as api_library_results_listResults } from "~backend/library/results";
import { saveResult as api_library_save_result_saveResult } from "~backend/library/save_result";

export namespace library {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.listAvatars = this.listAvatars.bind(this)
            this.listFits = this.listFits.bind(this)
            this.listResults = this.listResults.bind(this)
            this.saveResult = this.saveResult.bind(this)
        }

        /**
         * Lists user's avatars with pagination.
         */
        public async listAvatars(params: RequestType<typeof api_library_avatars_listAvatars>): Promise<ResponseType<typeof api_library_avatars_listAvatars>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/library/avatars`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_library_avatars_listAvatars>
        }

        /**
         * Lists user's fits with pagination.
         */
        public async listFits(params: RequestType<typeof api_library_fits_listFits>): Promise<ResponseType<typeof api_library_fits_listFits>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/library/fits`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_library_fits_listFits>
        }

        /**
         * Lists user's try-on results with pagination.
         */
        public async listResults(params: RequestType<typeof api_library_results_listResults>): Promise<ResponseType<typeof api_library_results_listResults>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/library/results`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_library_results_listResults>
        }

        /**
         * Saves a completed try-on result to user's gallery.
         */
        public async saveResult(params: RequestType<typeof api_library_save_result_saveResult>): Promise<ResponseType<typeof api_library_save_result_saveResult>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/library/save-result`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_library_save_result_saveResult>
        }
    }
}


export namespace shared {
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { retry as api_tryon_retry_retry } from "~backend/tryon/retry";
import { start as api_tryon_start_start } from "~backend/tryon/start";
import { status as api_tryon_status_status } from "~backend/tryon/status";

export namespace tryon {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.retry = this.retry.bind(this)
            this.start = this.start.bind(this)
            this.status = this.status.bind(this)
        }

        /**
         * Retries a failed try-on job.
         */
        public async retry(params: RequestType<typeof api_tryon_retry_retry>): Promise<ResponseType<typeof api_tryon_retry_retry>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/tryon/retry`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tryon_retry_retry>
        }

        /**
         * Starts a virtual try-on job using Nano Banana API.
         */
        public async start(params: RequestType<typeof api_tryon_start_start>): Promise<ResponseType<typeof api_tryon_start_start>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/tryon`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tryon_start_start>
        }

        /**
         * Gets the status and result of a try-on job.
         */
        public async status(params: { job_id: number }): Promise<ResponseType<typeof api_tryon_status_status>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/api/tryon/${encodeURIComponent(params.job_id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tryon_status_status>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
